blank_issues_enabled: false
contact_links:
  - name: AntiScamBot Discord Server / Lostis Discord Server 
    url: https://discord.gg/5RrjAHubS6
    about: @2Lost4This Discord Server but for AntiScamBot too.
  - name: AntiScamBot Security Bug Bounty
    email: security@invalidlenni.de
    about: Please report security vulnerabilities
